src/Entity/SubItemMenu.php
<?php

namespace App\Entity;

use App\Repository\SubItemMenuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubItemMenuRepository::class)]
class SubItemMenu
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?bool $action = null;

    #[ORM\Column(length: 255)]
    private ?string $item_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $item_link = null;

    #[ORM\ManyToMany(targetEntity: MenuOneItem::class, mappedBy: 'MenuSubMenu')]
    private Collection $menuitems;

    public function __construct()
    {
        $this->menuitems = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->item_name ?? '';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isAction(): ?bool
    {
        return $this->action;
    }

    public function setAction(?bool $action): self
    {
        $this->action = $action;

        return $this;
    }

    public function getItemName(): ?string
    {
        return $this->item_name;
    }

    public function setItemName(string $item_name): self
    {
        $this->item_name = $item_name;

        return $this;
    }

    public function getItemLink(): ?string
    {
        return $this->item_link;
    }

    public function setItemLink(?string $item_link): self
    {
        $this->item_link = $item_link;

        return $this;
    }

    /**
     * @return Collection<int, MenuOneItem>
     */
    public function getMenuitems(): Collection
    {
        return $this->menuitems;
    }

    public function addMenuitem(MenuOneItem $menuitem): self
    {
        if (!$this->menuitems->contains($menuitem)) {
            $this->menuitems->add($menuitem);
            $menuitem->addMenuSubMenu($this);
        }

        return $this;
    }

    public function removeMenuitem(MenuOneItem $menuitem): self
    {
        if ($this->menuitems->removeElement($menuitem)) {
            $menuitem->removeMenuSubMenu($this);
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Scientist;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends BaseController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {
        $this->data['info'] = '1';

        $this->data['Scientist'] = $this->getScientist();

        return $this->baseRender(
            'base.html.twig',
            [
                'controller' => 'main',
                'data' => $this->data,
            ]
        );
    }

    public function getScientist()
    {
        return $this->doctrine->getRepository(Scientist::class)
            ->getActiveScientist();
    }
}

templates/main/footer.html.twig
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">© 2021-20...</small>
            </div>
            <div class="col-6 col-md">
                <h5>Предметная область</h5>
                <p> wikipedia</p>
            </div>
            <div class="col-6 col-md">
                <h5>Resources</h5>
                <p>документация</p>
            </div>
            <div class="col-6 col-md">
                <h5>Контакты</h5>
                <a href="vk.ru">Разработчик</a>
            </div>
        </div>
    </footer>
</html>

templates/main/header.html.twig
<!DOCTYPE html>
<meta charset="utf-8">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
{#        <script type="text/javascript" src="{{ absolute_url('public/build/app.js') }}"></script>#}
{#        <script type="text/javascript" src="{{ absolute_url('public/runtime.js') }}"></script>#}
    {% endblock %}
    <title>
        {% block title %}
            Главная
        {% endblock %}
    </title>
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}
</head>

templates/main/nav_menu.html.twig
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
            <nav class="menu">
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    {% for key,item in menu.SubMenu %}
                    <li>
                       <a href="{{ item.item_link|default(false) }}"
                          class="nav-link px-2 text-white">{{item.itemName}}</a>
                        {% if (item.MenuSubMenu|default(false)) %}
                        <ul class="sub_menu">
                            {% for item_2 in item.MenuSubMenu %}
                                <li>
                                    <a class=" nav-link px-2 text-white" href="{{ item_2.item_link }}">{{ item_2.item_name }}</a>
                                </li>
                            {% endfor %}
                       </ul>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </nav>
            <div class="text-end">
                <button type="button" class="btn me-2"><a class="btn btn-outline-light"  href="">Вход</a></button>
                <button type="button" class="btn btn-warning">Зарегистрироваться</button>
            </div>
        </div>
    </div>
</header>